### PR TITLE
430 fix get started

### LINKED ISSUE #430: flexfarmer get-started page missing link to other get-started page
Someone on reddit just comment on this line on https://www.flexpool.io/get-started/xch/flexfarmer/

PlotNFT joined to Flexpool (see getting started for instructions).

That should point people at the main Chia get-started page since the regular chia client is required for the plotnft part of the process. 

Let's add something like:

If you need to set up the Chia client to manage your PlotNFT, see our _CLI_ and _GUI_ instructions for getting started with the official Chia client. 

CLI link: https://www.flexpool.io/get-started/xch/XCH-CLI/
GUI link: https://www.flexpool.io/get-started/xch/XCH-GUI/

### PR DESCRIPTION
**Pull request by aminick**
Fix #430 
Farm_Chia__XCH__using_FlexFarmer___Flexpool_io

### CODE REVIEW

File: components/guides/GuideList.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ function GuideList({ listItems }) {
   return (
     <ul>
       {listItems.map((item) => (
-        <li key={item.text}>{item.text}</li>
+        <li key={item.text} dangerouslySetInnerHTML={{ __html: item.text }} />
```
Comment (AlexSSD7) [inline components/guides/GuideList.tsx:9]: Please never use `dangerouslySetInnerHTML`. It is dangerous because we don't really trust translators.

Use `<Trans>` component instead. (see examples by searching it in the codebase)

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]

File: components/guides/GuideList.tsx (hunk 1 above)
Comment (aminick) [reply components/guides/GuideList.tsx:9]: Good point

File: public/locales/en-US/guide-flexfarmer.json [hunk 2]
```diff
@@ -11,7 +11,9 @@
       { "text": "At least 128MB available RAM." },
       { "text": "Initialized Plot NFT (Made via GUI or CLI)." },
       { "text": "Plots bound to that Plot NFT." },
-      { "text": "PlotNFT joined to Flexpool (see getting started for instructions)." }
+      {
+        "text": "PlotNFT joined to Flexpool (To manage your PlotNFT with the Chia client, see our <a href='https://www.flexpool.io/get-started/xch/XCH-CLI/'>CLI</a> and <a href='https://www.flexpool.io/get-started/xch/XCH-GUI/'>GUI</a> instructions)."
```
Comment (AlexSSD7) [inline public/locales/en-US/guide-flexfarmer.json:15]: Can you please move `hrefs` to the Trans components section? And use `LinkOut` instead of `a` for links?

So you will just have `<guilink>` and `<clilink>` components by doing this:

```tsx
<li key={item.text}>
          <Trans
            components={{
              a: <a href="" target="__blank" />,
              guilink: <LinkOut href="https://www.flexpool.io/get-started/xch/XCH-GUI/" target="__blank" />,
              clilink: <LinkOut href="https://www.flexpool.io/get-started/xch/XCH-CLI/" target="__blank" />
            }}
          >
            {item.text}
          </Trans>
        </li>
```

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]

File: components/guides/GuideList.tsx [hunk 3]
```diff
@@ -10,7 +11,19 @@ function GuideList({ listItems }) {
         <li key={item.text}>
           <Trans
             components={{
-              a: <a target="__blank" />,
+              a: <a href="" target="__blank" />,
+              guilink: (
+                <LinkOut
+                  href="https://www.flexpool.io/get-started/xch/XCH-GUI/"
+                  target="__blank"
```
Comment (AlexSSD7) [inline components/guides/GuideList.tsx:18]: Forgot to add: target is already prefilled by __blank, so no need to have it.

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]

**Review by AlexSSD7 — APPROVED** [review]
